Privileged API spec improvements
nationalarchives/ds-caselaw-public-access-service pull request #46
Opened 2022-07-08 16:39 UTC by dragon-dxw

[Trello](https://trello.com/c/uY8r4n9J/321-create-openapi-spec-for-privileged-api)

Addresses the discussion points about tightening up the spec:

* descoped metadata
* return who has lock if checkout/write attempted
* add input data to write
* reading checkout status descoped
* explicitly state XML output

2022-07-11 09:05 UTC, dragon-dxw commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create OpenAPI spec for privileged API](https://trello.com/c/uY8r4n9J/321-create-openapi-spec-for-privileged-api)

2022-07-13 15:36 UTC, lozette requested changes
Small bit of commit-shuffling to be done, but otherwise great!

2022-07-13 15:36 UTC, lozette commented on doc/openapi/privileged_api.yml
> +
I think the contents of the next commit were meant to go into this commit?

2022-08-24 14:49 UTC, lozette approved these changes

2022-08-24 16:12 UTC, merged