Add VPN related documentation
nationalarchives/ds-caselaw-public-access-service pull request #67
Opened 2022-08-18 15:49 UTC by rjw1

We use 2 VPNs for caselaw stuff. This documents their usage and how to set
up the AWS VPN.

2022-08-22 15:47 UTC, lozette requested changes

2022-08-22 15:47 UTC, lozette commented on vpn.md
> +rough notes for setting up a cleint vpn endpoint.
`client`

2022-08-22 15:47 UTC, lozette commented on vpn.md
> +  - take an old one and replace the certificate and key in the `<cert>` and `<key>` sections with the one for the user found in `/mnt/efs/easy-rsa-ca/pki/{issued,private}`
Extra space at the start of this line

2022-08-24 17:04 UTC, dragon-dxw approved these changes

2022-08-25 10:28 UTC, merged